#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yandriie <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/10/24 17:42:25 by yandriie          #+#    #+#              #
#    Updated: 2017/10/24 19:52:07 by yandriie         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = ft_display_file

all : $(NAME)

$(NAME):
	gcc ft_display_file.c -o ft_display_file

clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f $(NAME)