#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yandriie <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/11/07 12:49:53 by yandriie          #+#    #+#              #
#    Updated: 2017/11/07 13:33:04 by yandriie         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = libft.a

all: $(NAME)

$(NAME): ft_atoi.o ft_bzero.o ft_islanum.o ft_isalpha.o ft_isascii.o ft_isdigit.o ft_isprint.o ft_isspace.o ft_itoa.o ft_lstadd.o ft_lstdel.o ft_lstdelone.o ft_lstiter.o ft_listmap.o ft_lstnew.o ft_memalloc.o ft_memccpy.o ft_memchr.o ft_memcmp.o ft_memcpy.o ft_memdel.o ft_memmove.o ft_memset.o ft_putchar.o ft_putchar_fd.o ft_putendl.o ft_putendl_fd.o ft_putnbr.o ft_putnbr_fd.o ft_putstr.o ft_putstr_fd.o ft_strcat.o ft_strchr.o ft_strclr.o ft_strcmp.o ft_strcpy.o ft_strdel.o ft_strdup.o ft_strequ.o ft_striter.o ft_striteri.o ft_strjoin.o ft_strlcat.o ft_strlen.o ft_strmap.o ft_strmapi.o ft_strncat.o ft_strncmp.o ft_strncpy.o ft_strnequ.o ft_strnew.o ft_strnstr.o ft_strrchr.o ft_strsplit.o ft_strstr.o ft_strtrim.o ft_tolower.o ft_toupper.o
	ar rc $(NAME)
	ranlib $(NAME)

ft_atoi.o: ft_atoi.c
	gcc -Wall -Wextra -Werror ft_atoi.c -o ft_atoi.o

ft_bzero.o: ft_bzero.c
	gcc -Wall -Wextra -Werror ft_bzero.c -o ft_bzero.o

ft_isalnum.o: ft_isalnum.c
	gcc -Wall -Wextra -Werror ft_isalnum.c -o ft_isalnum.o

ft_isalpha.o: ft_isalpha.c
	gcc -Wall -Wextra -Werror ft_isalpha.c -o ft_isalpha.o

ft_isascii.o: ft_isascii.c
	gcc -Wall -Wextra -Werror ft_isascii.c -o ft_isascii.o

ft_isdigit.o: ft_isdigit.c
	gcc -Wall -Wextra -Werror ft_isdigit.c -o ft_isdigit.o

ft_isprint.o: ft_isprint.c
	gcc -Wall -Wextra -Werror ft_isprint.c -o ft_isprint.o

ft_isspace.o: ft_isspace.c
	gcc -Wall -Wextra -Werror ft_isspace.c -o ft_isspace.o

ft_itoa.o: ft_itoa.c
	gcc -Wall -Wextra -Werror ft_itoa.c -o ft_itoa.o

ft_lstadd.o: ft_lstadd.c
	gcc -Wall -Wextra -Werror ft_lstadd.c -o ft_lstadd.o

ft_lstdel.o: ft_lstdel.c
	gcc -Wall -Wextra -Werror ft_lstdel.c -o ft_lstdel.o

ft_lstdelone.o: ft_lstdelone.c
	gcc -Wall -Wextra -Werror ft_lstdelone.c -o ft_lstdelone.o

ft_lstiter.o: ft_lstiter.c
	gcc -Wall -Wextra -Werror ft_lstiter.c -o ft_lstiter.o

ft_lstmpa.o: ft_lstmap.c
	gcc -Wall -Wextra -Werror ft_lstmap.c -o ft_lstmap.o

ft_lstnew.o: ft_lstnew.c
	gcc -Wall -Wextra -Werror ft_lstnew.c -o ft_lstnew.o

ft_memalloc.o: ft_memalloc.c
	gcc -Wall -Wextra -Werror ft_memalloc.c -o ft_memalloc.o

ft_memccpy.o: ft_memccpy.c
	gcc -Wall -Wextra -Werror ft_memccpy.c -o ft_memccpy.o

ft_memchr.o: ft_memchr.c
	gcc -Wall -Wextra -Werror ft_memchr.c -o ft_memchr.o

ft_memcmp.o: ft_memcmp.c
	gcc -Wall -Wextra -Werror ft_memcmp.c -o ft_memcmp.o

ft_memcpy.o: ft_memcpy.c
	gcc -Wall -Wextra -Werror ft_memcpy.c -o ft_memcpy.o

ft_memdel.o: ft_memdel.c
	gcc -Wall -Wextra -Werror ft_memdel.c -o ft_memdel.o

ft_memmove.c: ft_memmove.c
	gcc -Wall -Wextra -Werror ft_memmove.c -o ft_memmove.o

ft_memset.o: ft_memset.c
	gcc -Wall -Wextra -Werror ft_memset.c -o ft_memset.o

ft_putchar.o: ft_putchar.c
	gcc -Wall -Wextra -Werror ft_putchar.c -o ft_putchar.o

ft_putchar_fd.o: ft_putchar_fd.c
	gcc -Wall -Wextra -Werror ft_putchar_fd.c -o ft_putchar-fd.o

ft_putendl.o: ft_putendl.c
	gcc -Wall -Wextra -Werror ft_putendl.c -o ft_putendl.o

ft_putendl_fd.o: ft_putendl_fd.c
	gcc -Wall -Wextra -Werror ft_putendl_fd.c -o ft_putendl_fd.o

ft_putnbr.o: ft_putnbr.c
	gcc -Wall -Wextra -Werror ft_putnbr.c -o ft_putnbr.o

ft_putnbr_fd.o: ft_putnbr_fd.c
	gcc -Wall -Wextra -Werror ft_putnbr_fd.c -o ft_putnbr_fd.o

ft_putstr.o: ft_putstr.c
	gcc -Wall -Wextra -Werror ft_putstr.c -o ft_putstr.o

ft_putstr_fd.o: ft_putstr_fd.c
	gcc -Wall -Wextra -Werror ft_putstr_fd.c -o ft_putstr_fd.o

ft_strcat.o: ft_strcat.c
	gcc -Wall -Wextra -Werror ft_strcat.c -o ft_strcat.o

ft_strchr.o: ft_strchr.c
	gcc -Wall -Wextra -Werror ft_strchr.c -o ft_strchr.o

ft_strclr.o: ft_strclr.c
	gcc -Wall -Wextra -Werror ft_strclr.c -o ft_strclr.o

ft_strcmp.o: ft_strcmp.c
	gcc -Wall -Wextra -Werror ft_strcmp.c -o ft_strcmp.o

ft_strcpy.o: ft_strcpy.c
	gcc -Wall -Wextra -Werror ft_strcpy.c -o ft_strcpy.o

ft_strdel.o: ft_strdel.c
	gcc -Wall -Wextra -Werror ft_strdel.c -o ft_strdel.o

ft_strdup.o: ft_strdup.c
	gcc -Wall -Wextra -Werror ft_strdup.c -o ft_strdup.o

ft_strequ.o: ft_strequ.c
	gcc -Wall -Wextra -Werror ft_strequ.c -o ft_strequ.o

ft_striter.o: ft_striter.c
	gcc -Wall -Wextra -Werror ft_striter.c -o ft_striter.o

ft_striteri.o: ft_striteri.c
	gcc -Wall -Wextra -Werror ft_striteri.c -o ft_striteri.o

ft_strjoin.o: ft_strjoin.c
	gcc -Wall -Wextra -Werror ft_strjoin.c -o ft_strjoin.o

ft_strlcat.o: ft_strlcat.c
	gcc -Wall -Wextra -Werror ft_strlcat.c -o ft_strlcat.o

ft_strlen.o: ft_strlen.c
	gcc -Wall -Wextra -Werror ft_strlen.c -o ft_strlen.o

ft_strmap.o: ft_strmap.c
	gcc -Wall -Wextra -Werror ft_strmap.c -o ft_strmap.o

ft_strmapi.o: ft_strmapi.c
	gcc -Wall -Wextra -Werror ft_strmapi.c -o ft_strmapi.o

ft_strncat.o: ft_strncat.c
	gcc -Wall -Wextra -Werror ft_strncat.c -o ft_strncat.o

ft_strncmp.o: ft_strncmp.c
	gcc -Wall -Wextra -Werror ft_strncmp.c -o ft_strncmp.o

ft_strncpy.o: ft_strncpy.c
	gcc -Wall -Wextra -Werror ft_strncpy.c -o ft_strncpy.o

ft_strnequ.o: ft_strnequ.c
	gcc -Wall -Wextra -Werror ft_strnequ.c -o ft_strnequ.o

ft_strnew.o: ft_strnew.c
	gcc -Wall -Wextra -Werror ft_strneq.c -o ft_strnew.o

ft_strnstr.o: ft_strnstr.c
	gcc -Wall -Wextra -Werror ft_strnstr.c -o ft_strnstr.o

ft_strrchr.o: ft_strrchr.c
	gcc -Wall -Wextra -Werror ft_strrchr.c -o ft_strrchr.o

ft_strsplit.o: ft_strsplit.c
	gcc -Wall -Wextra -Werror ft_strsplit.c -o ft_strsplit.o

ft_strstr.o: ft_strstr.c
	gcc -Wall -Wextra -Werror ft_strstr.c -o ft_strstr.o

ft_strsub.o: ft_strsub.c
	gcc -Wall -Wextra -Werror ft_strsub.c -o ft_strsub.o

ft_strtrim.o: ft_strtrim.c
	gcc -Wall -Wextra -Werror ft_strtrim.c -o ft_strsub.o

ft_tolower.o: ft_tolower.c
	gcc -Wall -Wextra -Werror ft_tolower.c -o ft_tolower.o

ft_toupper.o: ft_toupper.c
	gcc -Wall -Wextra -Werror ft_toupper.c -o ft_toupper.o

clean:
	/bin/rm -f $(NAME)

fclean: clean
	/bin/rm -f *.o *.gch

re: fclean all